# Generated by Django 4.1.8 on 2023-09-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErhtvFaaAdatlap',
            fields=[
                ('prj_id', models.IntegerField()),
                ('prj_rnev', models.CharField(max_length=25)),
                ('prj_ev', models.SmallIntegerField()),
                ('prj_elozo_faaprj_id', models.IntegerField()),
                ('prj_faa_kesz', models.SmallIntegerField()),
                ('prj_ert_ddatum', models.DateTimeField()),
                ('prj_ert_dszog', models.DecimalField(decimal_places=1, max_digits=5)),
                ('ert_id', models.IntegerField()),
                ('ert_azo', models.CharField(max_length=25)),
                ('mvp_id', models.IntegerField()),
                ('mvp_azo', models.CharField(max_length=25)),
                ('mvp_eov_x', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mvp_eov_y', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mvp_tszfm', models.DecimalField(decimal_places=0, max_digits=4)),
                ('jkv_adat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('faasz_felmeresdatum', models.DateTimeField(blank=True, null=True)),
                ('faasz_felmero_id', models.SmallIntegerField()),
                ('szm_rnev', models.CharField(max_length=25)),
                ('faasz_jkonyvezo_id', models.SmallIntegerField()),
                ('jkv_szm_rnev', models.CharField(max_length=25)),
                ('faasz_adatlap_ssz', models.CharField(max_length=5)),
                ('faasz_modszertan_id', models.SmallIntegerField()),
                ('mod_rnev', models.CharField(max_length=5)),
                ('faa_modszertan_id', models.SmallIntegerField()),
                ('mod_faa_rnev', models.CharField(max_length=5)),
                ('faa_adat_id', models.IntegerField(blank=True, null=True)),
                ('zarodas_ossz', models.SmallIntegerField(blank=True, null=True)),
                ('boritas_flkszint', models.SmallIntegerField(blank=True, null=True)),
                ('boritas_alkszint', models.SmallIntegerField(blank=True, null=True)),
                ('boritas_csjszint', models.SmallIntegerField(blank=True, null=True)),
                ('boritas_gyszint', models.SmallIntegerField(blank=True, null=True)),
                ('lekesseg_id', models.SmallIntegerField(blank=True, null=True)),
                ('lek_rnev', models.CharField(blank=True, max_length=5, null=True)),
                ('faa_adat_kieg', models.CharField(blank=True, max_length=500, null=True)),
                ('faa_kesz', models.SmallIntegerField()),
                ('ksz_azo', models.CharField(max_length=5)),
                ('fae_mvhanyad', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fhf_mvhanyad', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'verbose_name': 'Faállomány adatlap',
                'verbose_name_plural': 'Faállomány adatlapok',
                'db_table': 'erhtv_faa_adatlap',
                'managed': False,
            },
        ),
    ]
